spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Logins?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 98625232

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 583196002877-7m2046jtpsj13lq3scfklk71nho42st1.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "http://localhost:8087/Stage/login/google/callback"
            scope:
              - email
              - profile
          facebook:
            clientId: 783678850163258
            clientSecret: 8e02b6eba9d24b627b04d3d1a6aff63f
            redirectUri: "http://localhost:8087/Stage/login/facebook/callback"
            scope:
              - email
              - public_profile
              - user_likes


          github:
            clientId: Iv1.f6f8358857e6a877
            clientSecret: 92b2312ecee50a750f3e22545a38a08318263189
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
          linkedin:
            clientId: 78sm5r1tnrrgye
            clientSecret: Zzt1sMcjbGOWbhbg
            redirectUri: "http://localhost:8087/Stage/login/linkedin/callback"
            scope: r_liteprofile r_emailaddress

        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

server:
    servlet:
      context-path: /Stage
    port: 8087
jwt:
  secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5NDQ2MDE1NiwiaWF0IjoxNjk0NDYwMTU2fQ.qabVB79RW2FUPapZKO7Mp5j4YMqmEFZBwb7bME4fQf8
  expiration: 3600
